import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
  "check":"اضغط للتاكد من حجز الكورس ",
          "1": "مرحبا",
          "2": "تسجيل الدخول إلى حسابك",
          "3": "أدخل بريدك الإلكتروني",
          "4": "ادخل رقمك السري",
          "5": "تسجيل الدخول",

          "I Paid and want to activate the course":"تم الدفع واريد تفعيل الكورس",
          "Donot press the button until you send total to vodafone cash number":"لا تضغط قبل ارسال الاجمالي عبر فودافون كاش",
          "6": "أنشئ حسابك",
          "7": "أدخل أسمك",
          "8": "انشاء الحساب",
          "9": "   طلاب \ كلية تجارة المنصورة ",
          "10": "اختار الفرقـة",
          "Next":"التالي",
          "11": "         البحث عن الفصول والدورات... ",
          "12": "الفرقة الاولي",
          "13": "الفرقة الثانية",
          "14": "الفرقة الثالثـة",
          "15": "الفرقة الرابعـة",
          "16": "الكورسـات المقتـرحة",
          "17": "الأكثر مبيعًا",
          "18": " تجــارة عربـي  ",
          "19": " تجــارة انجليزي  ",
          "20": "مواد الفرقــة",
          "21": " اختار الدكتور",
          "22": "محتويات الدورة",
          "23": "اللغة",
          "Wallet number":"رقم المحفظة",
          "Chat Us":"تواصل معنا",
          "Enter name":"ادخل اسمك",
          "24": "مشاركة التطبيق",
          "25": "تسجيل خروج",
          "26": "الصفحة الرئيسية",
          "27": "المفضلة",
          "28": "دوراتي",
          "29": "البروفايل",
          "Pay With vodafone cash":"الدفع عن طريق فودافون كاش",
          "Total":" الاجمالي ",
          "30": "اختـار اللغة",
          "31": "العـربية",
          "32": "الانجليـزيـة",
          "33": "فـارغة",
          "34": "تصفح الكورسات",
          "35": " ليس لديك حساب؟",
          "36": "انشاء حساب",
          "Our Vodafone Cash Number":"رقم فودافون كاش الخاص بنا",
          "Send total to activate the course":"ارسل الاجمالي لرقم فودافون كاش"
        },
        "en": {
          "1": "Hello",
          "2": "Sign in to your account",
          "3": "Enter your Email",
          "4": "Enter your password",
          "5": "Sign in",
          "6": "Create your account",
          "7": "Enter your Name",
          "8": "Create account",
          "9": "Students Of Commerce\ El Mansoura",
          "10": "Choose Your Level",
          "11": "Search for classes, courses...",
          "12": "Level One",
          "13": "Level Two",
          "14": "Level Three",
          "15": "Level Four",
          "16": "Suggestions",
          "17": "Most Selling ",
          "18": "Arabic Commerce",
          "19": "English Commerce",
          "20": "Level Courses",
          "21": "Doctors Course",
          "22": "Course contents",
          "23": "Languages",
          "24": "Share App",
          "25": "Log out",
          "26": "Home",
          "27": "Favourite",
          "28": "my courses",
          "29": "Profile",
          "30": "Choose Language",
          "31": "Arabic",
          "32": "English",
          "33": "Empty",
          "Next":"Next",
          "Total":" Total ",
          "34": "Explore Course",
          "35": "Dont\'t have an account? ",
          "I Paid and want to activate the course":"I Paid and want to activate the course",
          "36": "Sign up",
          "Chat Us":"Chat Us",
          "Wallet number":"Wallet number",
          "Send total to activate the course":"Send total to activate the course",
          "Our Vodafone Cash Number":"Our Vodafone Cash Number",
          "Enter name":"Enter your name ",
          "Pay With vodafone cash":"Pay With vodafone cash",
       "check":"Check if this course available for you or not",
          "Donot press the button until you send total to vodafone cash number":"Donot press the button until you send total to vodafone cash number"
        },
      };
}
